# 都合のいい個眼視野角を使用

settings = {
    'output_width': 1920,
    'output_height': 1080,
    'image_format': '../step1-panorama-rendering/output_color/*.png',
    'interommatidial_angle': 1.5,  # 個眼間角度の初期値
    'ommatidium_angle': 15,  # 個眼視野角の初期値
    'ommatidium_count': 25,  # 個眼個数の初期値
    'theta': 0,
    'phi': 0,
    'filter': 'hexagonal_depth_gaussian',  # フィルタの初期設定
    'view_mode': 'color',  # 表示モードの初期設定
    'debug_mode': False,  # デバッグモードの初期設定
    'blur_size': 30  # ブラーサイズの初期値
}