output_width= 1920 # 出力画像 width
output_height= 1080 # 出力画像 height
image_format= "../step1-panorama-rendering/output_color/*.png" # 入力画像のパス
interommatidial_angle= 1.5  # 個眼間角度の初期値
ommatidium_angle= 1.5  # 個眼視野角の初期値
ommatidium_count= 25  # 個眼個数の初期値
theta= 0 # カメラの水平角度の初期値
phi= 0 # カメラの垂直角度の初期値
filter= "hexagonal_depth_gaussian"  # フィルタの初期設定
view_mode= "color"  # 表示モードの初期設定
debug_mode= false  # デバッグモードの初期設定
blur_size = 60  # ブラーサイズの初期値
frame = 0 # フレーム数の初期値
